<?php 

function find_user($authentication, $userabbreviation)
{	
	$session = $authentication[0];
	$cookie1 = $authentication[1];
	$cookie2 = $authentication[2];

	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, "https://tutorial.microstrategy.com/MicroStrategyLibrary/api/users?abbreviationBegins=".$userabbreviation."&limit=-1");
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
	
	
	$headers = array();
	$headers[] = "Accept: application/json";
	$headers[] = "X-Mstr-Authtoken: ".$session;
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	curl_setopt($ch, CURLOPT_COOKIE, $cookie1.';'.$cookie2);
	
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close ($ch);
	return($result);
}

function get_user_id($user_information)
{
	$user_response_decode = json_decode($user_information);
	$user_id = $user_response_decode[0]->id;
	if ($user_id == '')
		echo '--> not found
';
	return $user_id;
}

?>