<?php 

function publish_dossier($authentication, $projectid, $dossierid, $userid)
{	
	$session = $authentication[0];
	$cookie1 = $authentication[1];
	$cookie2 = $authentication[2];

	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, "https://tutorial.microstrategy.com/MicroStrategyLibrary/api/library");
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"id\": \"".$dossierid."\",\"recipients\": [{\"id\":\"".$userid."\"}],\"isInstance\": false}");
	curl_setopt($ch, CURLOPT_POST, 1);
	
	$headers = array();
	$headers[] = "Content-Type: application/json";
	$headers[] = "Accept: */*";
	$headers[] = "X-Mstr-Authtoken: ".$session;
	$headers[] = "X-Mstr-Projectid: ".$projectid;
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	curl_setopt($ch, CURLOPT_COOKIE, $cookie1.';'.$cookie2);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close ($ch);
	print_r($result);
}
?>